export const blogData = [
    {
        id: 1,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/ben-masora-Oy5IKUo8lZM-unsplash-1000x600.jpg",
        imageAlt: "ben-masora",
        imageLink: "/",
        categories: ["Entertainment", "Technology"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "Together We Can Make The World A Better Place",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. You meet someone, they introduce themselves, and two minutes later you can’t recall their name. It happens all the time Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. You meet someone, they introduce themselves, and two minutes later you can’t recall their name. It happens all the time Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. You meet someone, they introduce themselves, and two minutes later you can’t recall their name. It happens all the time Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. ",
        comments: "0",
        views: "501",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 2,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/brooke-lark-atzWFItRHy8-unsplash-1000x600.jpg",
        imageAlt: "brooke-lark",
        imageLink: "/",
        categories: ["Health", "Life Style"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "It Really Have Good Feeling When You Enjoy Nature",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "430",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 3,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/mihai-stefan-658815-unsplash-1000x600.jpg",
        imageAlt: "mihai-stefan",
        imageLink: "/",
        categories: ["Entertainment", "Life Style"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "Best Dressed Girl in Fashion Industry in 2021",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "377",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 4,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/cleyton-ewerton-N3JngnkuyRs-unsplash-1000x600.jpg",
        imageAlt: "cleyton-ewerton",
        imageLink: "/",
        categories: ["Illustration", "Life Style"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "What It Feels Like to No Longer Worry About Money",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "397",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 5,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/jordan-whitfield-qODM8pfwRO4-unsplash-1000x600.jpg",
        imageAlt: "ordan-whitfield",
        imageLink: "/",
        categories: ["Entertainment", "Typography"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "Mental Shoot Tips to Cope With the End of Summer",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "336",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 6,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/najla-cam-F71ZHHBYs3w-unsplash-1000x600.jpg",
        imageAlt: "najla-cam",
        imageLink: "/",
        categories: ["Music", "Travel"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "What to Think About When Everything Goes Wrong",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "386",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 7,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/ben-masora-Oy5IKUo8lZM-unsplash-1000x600.jpg",
        imageAlt: "ben-masora",
        imageLink: "/",
        categories: ["Entertainment", "Technology"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "Together We Can Make The World A Better Place",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "501",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 8,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/mihai-stefan-658815-unsplash-1000x600.jpg",
        imageAlt: "mihai-stefan",
        imageLink: "/",
        categories: ["Entertainment", "Life Style"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "Best Dressed Girl in Fashion Industry in 2021",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "377",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 9,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/brooke-lark-atzWFItRHy8-unsplash-1000x600.jpg",
        imageAlt: "brooke-lark",
        imageLink: "/",
        categories: ["Health", "Life Style"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "It Really Have Good Feeling When You Enjoy Nature",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "430",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 10,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/cleyton-ewerton-N3JngnkuyRs-unsplash-1000x600.jpg",
        imageAlt: "cleyton-ewerton",
        imageLink: "/",
        categories: ["Illustration", "Life Style"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "What It Feels Like to No Longer Worry About Money",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "397",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 11,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/najla-cam-F71ZHHBYs3w-unsplash-1000x600.jpg",
        imageAlt: "najla-cam",
        imageLink: "/",
        categories: ["Music", "Travel"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "What to Think About When Everything Goes Wrong",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "386",
        readingTime: "3",
        readMoreLink: "/"
    },
    {
        id: 12,
        image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/jordan-whitfield-qODM8pfwRO4-unsplash-1000x600.jpg",
        imageAlt: "ordan-whitfield",
        imageLink: "/",
        categories: ["Entertainment", "Typography"],
        author: { image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/nora-hutton-tCJ44OIqceU-unsplash.jpg", imageAlt: "Alice", firstName: "Alice ", lastName: "Qelvin", authorLink: "/", postDate: "November 18, 2021" },
        title: "Mental Shoot Tips to Cope With the End of Summer",
        titleLink: "/",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in...",
        comments: "0",
        views: "336",
        readingTime: "3",
        readMoreLink: "/"
    },
];
