export const featuredPostsData = [{
    id: 1,
    image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/ben-masora-Oy5IKUo8lZM-unsplash-1000x600.jpg",
    imageAlt: "ben-masora",
    imageLink: "/",
    author: { firstName: "Alice ", lastName: "Qelvin", authorLink: "/" },
    title: "Together We Can Make The World A Better Place",
    titleLink: "/",
},
{
    id: 2,
    image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/brooke-lark-atzWFItRHy8-unsplash-1000x600.jpg",
    imageAlt: "brooke-lark",
    imageLink: "/",
    author: { firstName: "Alice ", lastName: "Qelvin", authorLink: "/" },
    title: "It Really Have Good Feeling When You Enjoy Nature",
    titleLink: "/",

},
{
    id: 3,
    image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/mihai-stefan-658815-unsplash-1000x600.jpg",
    imageAlt: "mihai-stefan",
    imageLink: "/",
    author: { firstName: "Alice ", lastName: "Qelvin", authorLink: "/" },
    title: "Best Dressed Girl in Fashion Industry in 2021",
    titleLink: "/",
},
{
    id: 4,
    image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/cleyton-ewerton-N3JngnkuyRs-unsplash-1000x600.jpg",
    imageAlt: "cleyton-ewerton",
    imageLink: "/",
    author: { firstName: "Alice ", lastName: "Qelvin", authorLink: "/" },
    title: "What It Feels Like to No Longer Worry About Money",
    titleLink: "/",
},
{
    id: 5,
    image: "https://demo.rivaxstudio.com/kayleen/wp-content/uploads/2021/11/najla-cam-F71ZHHBYs3w-unsplash-1000x600.jpg",
    imageAlt: "najla-cam",
    imageLink: "/",
    author: { firstName: "Alice ", lastName: "Qelvin", authorLink: "/" },
    title: "What to Think About When Everything Goes Wrong",
    titleLink: "/",
},

]